version: '2'
services:
    furymusicprime-app:
        image: furymusicprime
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://furymusicprime-mysql:3306/furymusicprime?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    furymusicprime-mysql:
        extends:
            file: mysql.yml
            service: furymusicprime-mysql
